server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/foodcourt
    username: ${DB_USER}
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${SECRET_KEY}
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  service-sid: ${TWILIO_SERVICE_SID}